### ISSUE TITLE
Update HTML and CSS to look more like designs

### ISSUE THREAD

**Issue by Bensonre** [cs361fall2018/project-dixonallstars#16]
should match the final designs provided more info can be found there

**Comment by xMestas** [comment]
Implements the bare bones structure of the design as well as the background.  Should be done about a week before the deadline to leave time for finalization in #19 and debugging.

**Comment by xMestas** [comment]
Partially implemented in #20.  Still need add background.

**Comment by xMestas** [comment]
Completed with background being added in #26
