### ISSUE TITLE
Create new controls and cursor

### ISSUE THREAD

**Issue by xMestas** [cs361fall2018/project-dixonallstars#18]
Rotate the ship with the arrow keys, and add the new cursor.  Maybe only for attacks or only for hovering on the opponents board?  Also check any bugs that may occur and make sure the new ship placement works correctly.

**Comment by xMestas** [comment]
Check font awesome for a cursor maybe?

**Comment by xMestas** [comment]
This can be done at any time since the other issues are not affected by it, but should be done at least a few days before the deadline to leave time for debugging.

**Comment by lkthang** [comment]
Somebody resolve this issue. I think I finished everything. Need a second pair of eyes.

**Comment by xMestas** [comment]
Implemented by #27
