### ISSUE TITLE
Make functionality of sonar attacks for the game and their limitations

### ISSUE THREAD

**Issue by xMestas** [cs361fall2018/project-dixonallstars#36]
**This is the most time intensive issues of this project.  It should be completed with at least 4 days before the deadline so it can be thoroughly tested and the UI can be implemented.**

Max of two sonars.  Cannot be done unless one ship is already sunk at least.  

Relates to Sprint 3 user story 4.  

Two ways to implement I can think of: 

Add sonars on to the attack results array.  For a square of spots, if there is not a hit or a miss or a sunk on the spot, if there is a ship add a AttackStatus.SonarFound to the list.  otherwise add AttackStatus.SonarNotFound to the list.  If this is the case, the front end will then just add two more cases to the loop where it is reading the attacks array to set a separate class for those that are found by sonar but not hit yet.  Make CSS for that class, add that class to the legend, and add sonar related errors to the error modal.  

Other implementation is make a separate array for the sonar that will have occupied or not occupied regardless of whether or not that spot is also recorded on the attacks array.  Front end will then read the new array in a separate loop and add on a class for occupied or not occupied.  CSS priority rules will then be applied to display for the correct color.  For example, if something is a hit and a found by sonar, it will have both classes on it.  CSS will make hit take priority over found and then it will have the hit color.  Hit Sunk CQHit and Miss will have priority over the occupied and notoccupied class.  

Backend and frontend **MUST** agree to a implementation BEFORE starting.

**Comment by Bensonre** [comment]
I was gonna do the first implementation you mentioned Thats what i thought of too. Will make sure chase is okay with that.

**Comment by xMestas** [comment]
Implemented by #41
